# Name: Zain Uddin

# Roll No: PIAIC86441

# Batch: 7

In [3]:
import numpy as np

In [5]:
# Method: 1
# Create an array.
np.array([8,6,4,4,1])

array([8, 6, 4, 4, 1])

In [28]:
# Method: 2
# Return a new array of given shape and type, filled with zeros.
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
# Method: 3
# Return a new array of given shape and type, filled with ones.
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# Method: 4
# Return a new array of given shape and type, without initializing entries.
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# Method: 5
# Return a sample (or samples) from the "standard normal" distribution.
np.random.randn(3,3)

array([[-1.76286611, -1.20010545,  1.52373839],
       [ 0.80735302,  0.5684383 ,  0.86330081],
       [ 1.45864208, -0.61202404, -0.0902828 ]])

In [24]:
# Method: 6
# Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(1,100,10)

array([20,  8, 68, 77,  4, 31, 40, 91,  7, 57])

In [30]:
# Method 7
# Return evenly spaced values within a given interval.
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
# Method 8
# Gives a new shape to an array without changing its data.
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
# Method 9
# Generates a random sample from a given 1-D array
np.random.choice([8,6,4,4,1],3)

array([6, 8, 4])

In [68]:
# Method 10
# Return an array of ones with the same shape and type as a given array.
a = np.random.randn(3,4)
np.ones_like(a)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
# Method 11
# Return an array of zeros with the same shape and type as a given array.
np.zeros_like(a)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
# Method 12
# Return a full array with the same shape and type as a given array.
np.full_like(a,10)

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [72]:
# Method 13
# Return a sorted copy of an array.
a=[8,6,4,4,1]
np.sort(a)

array([1, 4, 4, 6, 8])

In [75]:
# Method 14
# Return elements chosen from `x` or `y` depending on `condition`.
a=np.array([8,6,4,4,1])
np.where(a<5,a,None)

array([None, None, 4, 4, 1], dtype=object)

In [81]:
# Method 15
# Return the elements of an array that satisfy some condition.
np.extract(a<5,a)

array([4, 4, 1])

In [121]:
# Method 16
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [139]:
# Method 17
# Return the identity array.
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [143]:
# Method 18
# Return the shape of an array.
a = np.empty((3,4))
np.shape(a)

(3, 4)

In [159]:
# Method 19
# Return the index of the elements that are non-zero.
a= np.array([0,8,6,4,4,0])
np.nonzero(a)

(array([1, 2, 3, 4], dtype=int64),)

In [169]:
# Method 20
# Calculate the sum of elements in the array.
a = np.arange(0,9).reshape(3,3)
print(a)
print("sum: ",np.sum(a))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
sum:  36


In [171]:
# Method 21
# Return the cumulative sum of array elements.
print(a)
print("cumsum:", a.cumsum())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
cumsum: [ 0  1  3  6 10 15 21 28 36]


In [173]:
# Method 22
# Return the cumulative product of array elements.
print(a)
print("cumprod:", a.cumprod())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
cumprod: [0 0 0 0 0 0 0 0 0]


In [175]:
# Method 23
# Return the mean value computed over the array
a.mean()

4.0

In [178]:
# Method 24
# Checks if every value is true in the array.
b= a<5
b.all()

False

In [184]:
# Method 25
# Draw samples from a uniform distribution.
np.random.uniform(1,25,size = (3,3))

array([[ 3.14321158, 19.98014491,  1.19361604],
       [17.18766915,  8.09531535, 22.7418383 ],
       [10.73019625, 24.3320065 ,  5.2748106 ]])

In [187]:
# Method 26
# # Draw samples from a normal distribution.
np.random.normal(1,25,size = (3,3))

array([[ -2.67559306, -11.21840391, -19.65380892],
       [ 24.62838993,   7.57537433,  13.66097626],
       [-35.83575878,   2.5266489 ,  30.09586087]])

In [189]:
# Method 27
# Return the number of dimensions of an array.
np.ndim(a)

2

In [192]:
# Method 28
# It tells data type.
a.dtype

dtype('int32')

In [194]:
# Method 29
# Checks if any of element in array is true or not.
print(b)
print(np.any(b))

[[ True  True  True]
 [ True  True False]
 [False False False]]
True


In [195]:
# Method 30
# Return unique elements of an array.
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [197]:
# Method 31
# Calculate square root of array elements.
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [198]:
# Method 32
# Return Transpose of an array.
np.transpose(a)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [199]:
# Method 33
# Return highest number of an array.
np.max(a)

8

In [201]:
# Method 34
# Return highest number of an array.
np.min(a)

0

In [203]:
# Method 35
# Add power to the elements of array
np.power(a,3)

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]], dtype=int32)

In [205]:
# Method 36
# Return the sum of diagonal elements of array.
np.trace(a)

12

In [207]:
# Method 37
# Return the floor of the input.
np.floor(a)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [209]:
# Method 38
# Return the ciel of the input.
np.ceil(a)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [210]:
# Method 39
# Return a round off value of array.
np.round(a)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [218]:
# Method 40
# Compares elements of two array and returns the greater one.
b= np.arange(8,-1,-1).reshape((3,3))
print("a:",a,"\n","b:",b)
np.maximum(a,b)

a: [[0 1 2]
 [3 4 5]
 [6 7 8]] 
 b: [[8 7 6]
 [5 4 3]
 [2 1 0]]


array([[8, 7, 6],
       [5, 4, 5],
       [6, 7, 8]])

In [221]:
# Method 41
# Calculate the exponential of all elements in the input array.
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [238]:
# Method 42
# Join a sequence of arrays along a new axis.
np.stack(a,axis=1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [236]:
# Method 43
# Stack arrays in sequence horizontally (column wise).
np.hstack((a,b))

array([[0, 1, 2, 8, 7, 6],
       [3, 4, 5, 5, 4, 3],
       [6, 7, 8, 2, 1, 0]])

In [250]:
# Method 44
# Split an array into multiple sub-arrays as views into `ary`.
np.split(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [247]:
# Method 45
# Split array into multiple sub-arrays horizontally
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [248]:
# Method 46
# Split array into multiple sub-arrays vertically
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [255]:
# Method 47
# Find indices where elements should be inserted to maintain order.
arr=np.array([1,2,3,4,5,6,7,8,9])
np.searchsorted(arr,5)

4

In [258]:
# Method 48
# Return Dot product of two arrays.
np.dot(a,b)

array([[ 9,  6,  3],
       [54, 42, 30],
       [99, 78, 57]])

In [259]:
# Method 49
# Return diagonal values of an array.
np.diag(a)

array([0, 4, 8])

In [261]:
# Method 50
# Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by `arr[obj]`.
np.delete(a,(1,),axis=0)

array([[0, 1, 2],
       [6, 7, 8]])